language: python
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - pip install pipenv codecov
  - pipenv install -d

# TODO: Run tox tests
script:
  - pipenv run coverage run tests.py

after_success:
  - codecov
